blank_issues_enabled: false
contact_links:
  - name: Pepe Emoji Server
    url: https://discord.gg/XUQAnkq2vy
    about: Please use this Discord Server to ask questions and get support. We don't answer questions here and they will likely be closed and redirected to the Discord server.
