name: Build and Test

on:
  push:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Node v14
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Retrieve yarn dependencies cache
        uses: actions/cache@v1
        with:
          path: ~/.cache/yarn
          key: ${{ runner.os }}-yarn-${{ hashFiles(format('{0}{1}', github.workspace, '/yarn.lock')) }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install dependencies
        run: yarn --frozen-lockfile
        env:
          NODE_OPTIONS: --max-old-space-size=4096

      - name: Run TypeScript compiler
        run: yarn build

  lint:
    name: ESLint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Node v14
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Retrieve yarn dependencies cache
        uses: actions/cache@v1
        with:
          path: ~/.cache/yarn
          key: ${{ runner.os }}-yarn-${{ hashFiles(format('{0}{1}', github.workspace, '/yarn.lock')) }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install dependencies
        run: yarn --frozen-lockfile
        env:
          NODE_OPTIONS: --max-old-space-size=4096

      - name: Run ESLint
        run: yarn lint
